### ISSUE TITLE
Downcast bug with joins related to existing methods

### ISSUE THREAD

**Issue by jwoertink** [anykeyh/clear#111]
I tried to make a small reproducible example, but my code is a bit too complicated to re-create this easily. So hopefully this will be enough info.

Basically what happens is, when you do multiple joins, and it looks like this:

```crystal
class User
  # setup stuff....
  has_many posts : Post
  has_many comments : Comment, through: Post

  def blurbs
    User.query
      .join("posts") { posts.id ==  users.post_id }
      .join("comments") { comments.post_id == posts.id }
  end
end
```

This will throw a compile time error with
```
BUG: trying to downcast Clear::Expression <- Comments::Collection
```

My guess is this has something to do with using `comments.post_id` or `posts.id` when this class already has those methods defined. A "temp" fix is replacing those with `var("comments", "post_id") == var("posts", "id")`. 

This happens on 0.27.2, and 0.28.0. I know this is more of a crystal bug as reported:

https://github.com/crystal-lang/crystal/issues/7584
https://github.com/crystal-lang/crystal/issues/7222
https://github.com/crystal-lang/crystal/issues/5363
https://github.com/crystal-lang/crystal/issues/5190

But I'm wondering if there's a fix we can do on the clear side to help circumvent this until it's fixed in the language? I have my fix in place which will work fine, but tracking this down was pretty difficult since it was at compile-time.

**Comment by anykeyh** [comment]
This is a bug of the compiler but in the mean time your code would not work even if the compiler wasn't crashing.

Your method `blurbs` should be static `def self.blurbs`, otherwise `posts` and `comments` are going to be resolved as `self.posts` and `self.comments` equivalent to this code:

```crystal
  def blurbs
    User.query
      .join("posts") { self.posts.id ==  users.post_id }
      .join("comments") { comments.post_id == self.posts.id }
  end
```

So `var` Is the way to go here. `raw` provide a more compact way of writing it: `raw("comments.post_id")` too.

Btw Lucky Record tackle this problem by adding `_` in front of the table/field name.

**Comment by anykeyh** [comment]
I'm closing this issue as there's nothing I can do on my side. Having a smarter Crystal compiler would be great but out of my scope and my coding skill :smile:
