### ISSUE TITLE
shards install not working on amber

### ISSUE THREAD

**Issue by wontruefree** [anykeyh/clear#112]
I think the `anykeyh/generate.cr` lib is failing when combined with other libraries.  I think it actually is conflicting with something in shards.

Is there any way to pull in that library or name it something more specific I am not sure there is a way around this issue with shards.

**Comment by anykeyh** [comment]
Any errors trace?

**Comment by wontruefree** [comment]
The error does not make much sense on its face.

```bash
Failed git ls-tree -r --full-tree --name-only v0.1.0 -- shard.yml (). Maybe a commit, branch or file doesn't exist?
```

You can reproduce this by running `amber new clear_test` and add amber to the `shards.yml` and see the errors.

**Comment by anykeyh** [comment]
That's might be an issue with generate.cr having no releases. I just created a v0.1.0 release; feel free to try again.

**Comment by anykeyh** [comment]
This is probably related to crystal 0.28. I'll update the shard to make it compatible with 0.28

**Comment by wontruefree** [comment]
Thanks that worked.
It looks like amber is not interested in having this be a supported ORM but I really like the idea of combining the two.

I see you have a CLI now.  Do you use this for webservers? What webserver do you use?

**Comment by anykeyh** [comment]
Clear is not mature enough to ensure a full support with Amber. Not because it's impossible but because I won't be able to handle the extra work anyway :-). 

If you want to connect the two library I would be glad to help anyway.

Otherwise, there's a CLI only supporting migration (up/down/status/rollback) you can call like this:

```crystal
if ARGV.size > 0 && ARGV[0] == "clear"
  ARGV.shift
  Clear::CLI.run
else
   run_server
end
```

Then you can call:

```
$ crystal src/app.cr -- clear migrate --help
```

As of now there's missing some documentations about migration. You might find some documentation in `manual_old/migration/Migration.md`

Finally, for webserver I'm using Kemal. I'm currently building a ~500 hours  application using Clear+Kemal in backend (RESTful API), with Webpack+Mithril+Bulma on front-end. It works like a charm, but it's not as productive as for example Rails. 

On other end, many bugs are catched on compile time, which is great.

I would recommend also [sentry](https://github.com/samueleaton/sentry) with Makefile for automatically recompiling the changes on your server.

**Comment by wontruefree** [comment]
that is great to hear I will look into that.
