### ISSUE TITLE
[question] importing model with existing uuid

### ISSUE THREAD

**Issue by alex-min** [anykeyh/clear#162]
Hi,

I had to modify the library to make import work with uuids which are already provided. in src/clear/extensions/uuid/uuid.cr

I've transformed:
```crystal
Clear::Model::HasSerialPkey.add_pkey_type "uuid" do
  column __name__ : UUID, primary: true, presence: true

  before(:validate) do |m|
      m.as(self).__name__ = UUID.random unless m.persisted?
  end
end

```

into:
```crystal
Clear::Model::HasSerialPkey.add_pkey_type "uuid" do
  column __name__ : UUID, primary: true, presence: true

  before(:validate) do |m|
    if !m.persisted? && m.as(self).__name__.nil?
      m.as(self).__name__ = UUID.random
    end
  end
end
```

Do you think it makes sense? If yes I can make a PR for it. The goal is to make something like 
```crystal
      u = User.new({id: UUID.new("5ca27508-f2ce-441b-b2cf-41134793e7a1"), name: "test"})
      User.import([u])
```
to work

**Comment by anykeyh** [comment]
That's make sense and it's a bug, thanks for pointing it out !

Feel free to provide PR, but you need to change `m.as(self).__name__.nil?` by `m.as(self).__name___column.value(nil).nil?` instead, because of the way [columns presence is working](https://clear.gitbook.io/project/model/column-types/model-definition#non-presence-vs-nil)

**Comment by alex-min** [comment]
Ah perfect, I missed that then, I'll make a PR for it later and try to add a small spec if possible.
