### ISSUE TITLE
Column does not exist error

### ISSUE THREAD

**Issue by jwoertink** [anykeyh/clear#41]
This one isn't really a "bug", but something that caught us off guard for a bit. If you have a model that joins some other tables, then you want to do where the model's table some column = whatever, there's a few ways you can do this. 

We had something like this:

```crystal
base_query.where({"actors.slug": slug})
```

This led to a postgres error "column actors.slug does not exist". This threw us off because that column DOES exist. It turns out that the query that was generated was 

```
WHERE "actors.slug" = 'harrison-ford'
```

The tricky part is the query should have been `WHERE "actors"."slug" = 'harrison-ford'` 😂  Maybe this is something that could be added in?

**Comment by anykeyh** [comment]
Hello !

I won't fix this one, because it's normal behavior ! I don't want to make specific test (e.g. if there's `.` inside the name of the variable, we cut...), since it is possible (but unlikely) to use `.` inside some column name in postgres.

For example:

```sql
SELECT 1 as "hello.world"; -- this work and can be fetched by Clear using your example above
```

However, you can rewrite like this:

```
base_query.where{ actors.slug == slug }

# or 
base_query.where{ var("actors", "slug") == slug }

# or
base_query.where("actors.slug = ?", slug)

# or even
base_query.where("actors.slug = :slug", {slug: slug})
```

Cheers 😄

**Comment by jwoertink** [comment]
Sounds good! Thanks for checking 😄
