### ISSUE TITLE
Unable to create nilable/optional belongs_to association

### ISSUE THREAD

**Issue by jackturnbull** [anykeyh/clear#76]
It looks like I'm struggling to create a belongs_to relationship with similar sample code as the previous issue. Is there anything additional required to make this register as optional?

```sql
CREATE TABLE users (
  id UUID PRIMARY KEY
);

CREATE TABLE agents (
  id UUID PRIMARY KEY,
  user_id UUID REFERENCES users (id)
);
```
```crystal
require "clear"

Clear::SQL.init("postgres://...")

class User
  include Clear::Model

  with_serial_pkey type: :uuid
  has_one agent : Agent
end

class Agent
  include Clear::Model

  with_serial_pkey type: :uuid
  belongs_to user : User?, foreign_key: "user_id"
end

user = User.create()
agent = Agent.create!()
```
```
Unhandled exception: Validation of the model failed:
 user_id: must be present (Clear::Model::InvalidModelError)
  from lib/clear/src/clear/model/modules/has_saving.cr:137:5 in 'save!'
  from bug.cr:13:3 in 'create!'
  from bug.cr:20:1 in '__crystal_main'
  from /usr/local/Cellar/crystal/0.27.0/src/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/local/Cellar/crystal/0.27.0/src/crystal/main.cr:86:7 in 'main'
  from /usr/local/Cellar/crystal/0.27.0/src/crystal/main.cr:106:3 in 'main'
```

**Comment by anykeyh** [comment]
Actually `belongs_to` generated method always return a nilable object. `user` will return `User?`, while `user!` will return `User` (or throw exception).

Your problem comes from the key value here (`user_id`) , you should add `key_type: UUID?` in your belongs_to declaration. This should solve your problem.

I think you found some points of improvement:
- The first point is I think should be able to infers the type of the foreign key using the type of the primary key of the model we try to reference, making the `key_type` argument very occasional.
- In this case, the question mark on the type would refers about the presence or not of the key_type, and your syntax will be valid and working perfectly.

**Comment by anykeyh** [comment]
Edit: I had to fix UUID (again), if you update the shard and apply the fix above it should work perfectly

**Comment by jackturnbull** [comment]
Good call and thanks for the fix. The `key_type: UUID` was a leftover from the previous example that I didn't have in my code itself but it seems like you caught this issue that I meant to reference. Can confirm it's working perfectly now! 😄
