### ISSUE TITLE
Syntax error when using custom converter

### ISSUE THREAD

**Issue by jwoertink** [anykeyh/clear#79]
I'm trying to follow [these docs](https://github.com/anykeyh/clear/blob/master/manual_old/model/TypeConversion.md) and make a custom converter, but I'm getting a syntax error.

```crystal
module CustomConverter
  def self.to_column(x) : Hash(String, String)?
  end

  def self.to_db(x : Hash(String, String)?)
  end
end

class Post
  include Clear::Model
  column id : Int64, primary: true
  column tags : Hash(String, String), converter: CustomConverter
end
```

Using this example, I get this error when compiling:

```
expanding macro
in macro 'finished' expanded macro: included:9, line 2:

   1.         __generate_relations
>  2.         __generate_columns
   3.         __init_default_factory
   4.

macro didn't expand to a valid program, it expanded to:

================================================================================
.....
--------------------------------------------------------------------------------
Syntax error in expanded macro: __generate_columns:330: expecting token ')', not 'nil'

      @tags_column : Clear::Model::Column(Hash(String, String), nil) =
                                                                ^
```

**Comment by anykeyh** [comment]
Oh, sorry for that but the converter documentation hasn't been updated yet. I revamped it in 0.5 as it was really messy and impossible to deal with Generic and Union types.

Sorry for that :sweat_smile: 

Here is the way to do it now:

```crystal
module CustomConverter
  def self.to_column(x) : Hash(String, String)?
    case x
    when Hash(String, String)?
      x
    when String
      #...
    else
      raise "Cannot convert to Custom from #{x.class}"
    end
  end

  def self.to_db(x : Hash(String, String)?)
    #...
  end
end

Clear::Model::Converter.add_converter("custom_converter", CustomConverter)

# ... Then in model:
column tags : Hash(String, String), converter: "custom_converter"
```

I didn't tested the code above, but here is a currently working converter extracted from a production project for a "money" type (basically fixed point decimal treated in db as integer):

```crystal

module Clear::Model::Converter::MoneyConverter
  def self.to_column(x) : Money?
    case x
    when Money?
      x
    when Number
      Money.new(x)
    when String
      Money.new(x.to_i)
    else
      raise "Cannot convert to Money from #{x.class}"
    end
  end

  def self.to_db(x : Money?)
    x ? x.raw : nil
  end
end

Clear::Model::Converter.add_converter("Money", Clear::Model::Converter::MoneyConverter)
```

## Basics rules of conversion

1) Converters are simple modules, so it must use static members.
2) Converters always convert from Union(Type | Nil)
3) Always have a case which returns itself (because for some quite complicated reasons converters are in some cases used internally to return itself value)
4) The type of the input for the conversion is given by crystal_pg shard. It may be a Slice(UInt8), a string etc... according to the structure in postgres
5) Convention: If you want a custom converter which doesn't map the type, go for lower case underscore. If you want a converter which map a structure or other, go for the name of the class/structure, as it will be picked by default.

Finally, if you need converter for type already existing in Postgres, I would be glad to make them standard into Clear. Interval and Inet4 are the next on my todo list ;-)

Cheers,

**Comment by jwoertink** [comment]
Oh nice. Ok, I'll try that out. If that works, then I'll close the issue out. Thanks!

**Comment by anykeyh** [comment]
Feel free to come back to me if it doesn't :+1:.

I'll update the documentation when I get some free time.

**Comment by jwoertink** [comment]
Ok, so far this is working nice for pulling the data out. However, pushing new back in seems to be a little tricky. For my `to_db` method, I have

```crystal
def self.to_db(x : Hash(String, String)?)
  raise x.inspect        
end
```

When I call `.save` on my model, it returns true. I was expecting it to raise an exception. 

```crystal
p = Post.find(1)
p.tags["testing"] = "testing"
p.save #=> true
q = Post.find(1)
q.tags["testing"]? #=> nil
```

**Comment by anykeyh** [comment]
I see that. The problem is the column is made dirty when `tags` is set. 
However here you call the `tags` getter to eventually change the field content. It's non-trivial and I don't know how ruby's active record handle it. I should research on the subject.

As of now, one work around would be to call:

```crystal
p.tags_column.dirty!
p.save
```

Not very user friendly I must admit.

**Comment by jwoertink** [comment]
sweet! Ok, that worked. I'm ok with "dirty" if it works. 😆 I'll make a note of that and just go that route for now. Thanks for the help!

**Comment by anykeyh** [comment]
This is now in the documentation: https://clear.gitbook.io/project/model/column-types/converters#declare-a-new-converter
